version: "3.7"

services:
  database:
    image: postgres
    container_name: rs-rentx-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rs-rentx-db
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: rs-rentx-redis
    ports:
      - 6379:6379
  # app:
  #   build: .
  #   container_name: rs-rentx-api
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
