name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: install dependencies
        run: yarn
        
      - name: build app
        run: yarn build
       
      - name: copy files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/app/rs-rentx-api"
      
      - name: multiple command via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/rs-rentx-api
            yarn
            ./node_modules/.bin/typeorm migration:run
            yarn start
      
